#############################################################################
# Makefile for building: homework-qmake.app/Contents/MacOS/homework-qmake
# Generated by qmake (3.1) (Qt 6.8.0)
# Project:  ../../homework-qmake.pro
# Template: app
# Command: /Users/stephenzeng/Qt/6.8.0/macos/bin/qmake6 -o homework-qmake.xcodeproj/project.pbxproj ../../homework-qmake.pro -spec macx-xcode -qtconf /Users/stephenzeng/Qt/6.8.0/ios/bin/target_qt.conf CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/stephenzeng/Qt/6.8.0/macos/bin/qmake6
homework-qmake.xcodeproj/project.pbxproj: ../../homework-qmake.pro /Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-ios-clang/qmake.conf /Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/spec_pre.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/qdevice.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/device_config.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/unix.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/mac.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/uikit.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/ios.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/sanitize.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/gcc-base.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/clang.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/clang-mac.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/uikit/clang.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/uikit/qmake.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/qconfig.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext__clip2tri.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext__clipper.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext__poly2tri.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_freetype.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_glslang_glslang.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_glslang_osdependent.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_glslang_spirv.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_harfbuzz.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_libpng.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_openwnn.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_pcre2.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_pinyin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_spirv_cross.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_tcime.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_charts.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_coap.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_coap_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core5compat.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core5compat_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_entrypoint_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphs.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphs_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphswidgets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpc.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpc_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpcquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_httpserver.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_httpserver_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsplatform.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_linguist.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_mqtt.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_mqtt_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opcua.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opcua_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_png_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobuf.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobuf_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtcoretypes.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtguitypes.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufwellknowntypes.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmeta.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_repparser.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxmlqml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensorsquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_spatialaudio.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachine.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachine_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachineqml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_vncserver.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_vncserver_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_vncserverquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannelquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webview.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webviewquick.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_assimp.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_darwinmediaplugin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_ffmpegmediaplugin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_open62541_backend.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_openglrenderer.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qcertonlybackend.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_quick3dprofiler.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qscnetworkreachability.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qscxmlecmascriptdatamodel.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsecuretransportbackend.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_mock.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechdarwin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtposition_nmea.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_quicklintplugin.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_rhirenderer.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qt_functions.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qt_config.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/exclusive_builds.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/sdk.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/sdk.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/toolchain.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/toolchain.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/default_pre.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/default_pre.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/default_pre.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/resolve_config.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/resolve_config.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/default_post.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/default_post.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/default_post.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/objective_c.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qml_debug.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/mac.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/warn_on.prf \
		../../iosInfo.plist \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/permissions.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qt.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/resources_functions.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/resources.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/moc.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/unix/opengl.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/unix/thread.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qmake_use.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/file_copies.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/rez.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/asset_catalogs.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/testcase_targets.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/testcase_targets.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/exceptions.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/yacc.prf \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/lex.prf \
		../../homework-qmake.pro \
		/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard \
		../../icons.qrc \
		qmake_resources.qrc \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/permissions/libqdarwinbluetoothpermission.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/platforms/libqios.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/iconengines/libqsvgicon.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqgif.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqicns.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqico.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqjpeg.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqmacheif.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqmacjp2.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqsvg.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqtga.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqtiff.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqwbmp.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqwebp.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_debugger.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_inspector.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_local.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_messages.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_native.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_preview.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_profiler.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_quick3dprofiler.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_server.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_tcp.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/networkinformation/libqscnetworkreachability.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/plugins/tls/libqsecuretransportbackend.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/libqtquick2plugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQml/libqmlplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQml/Models/libmodelsplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQml/WorkerScript/libworkerscriptplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Dialogs/libqtquickdialogsplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Dialogs/quickimpl/libqtquickdialogs2quickimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Templates/libqtquicktemplates2plugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/libqtquickcontrols2plugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/impl/libqtquickcontrols2implplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Material/impl/libqtquickcontrols2materialstyleimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Imagine/impl/libqtquickcontrols2imaginestyleimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Fusion/impl/libqtquickcontrols2fusionstyleimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/FluentWinUI3/libqtquickcontrols2fluentwinui3styleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/iOS/libqtquickcontrols2iosstyleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Basic/libqtquickcontrols2basicstyleplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Universal/impl/libqtquickcontrols2universalstyleimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Window/libquickwindowplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/FluentWinUI3/impl/libqtquickcontrols2fluentwinui3styleimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Effects/libeffectsplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Shapes/libqmlshapesplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/iOS/impl/libqtquickcontrols2iosstyleimplplugin.prl \
		/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Basic/impl/libqtquickcontrols2basicstyleimplplugin.prl
	$(QMAKE) -o homework-qmake.xcodeproj/project.pbxproj ../../homework-qmake.pro -spec macx-xcode -qtconf /Users/stephenzeng/Qt/6.8.0/ios/bin/target_qt.conf CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/spec_pre.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/qdevice.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/device_config.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/unix.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/mac.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/uikit.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/ios.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/sanitize.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/gcc-base.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/gcc-base-mac.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/clang.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/clang-mac.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/uikit/clang.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/common/uikit/qmake.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/qconfig.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext__clip2tri.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext__clipper.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext__poly2tri.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_freetype.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_glslang_glslang.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_glslang_osdependent.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_glslang_spirv.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_harfbuzz.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_libjpeg.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_libpng.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_openwnn.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_pcre2.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_pinyin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_spirv_cross.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_ext_tcime.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3danimation.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dcore.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dextras.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dinput.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3drender.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_charts.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_charts_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_chartsqml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_chartsqml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_coap.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_coap_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core5compat.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core5compat_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_declarativeopcua.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_entrypoint_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_example_icons_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_freetype_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphs.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphs_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphswidgets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_graphswidgets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpc.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpc_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpcquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_grpcquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_help.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_httpserver.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_httpserver_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_jpeg_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsplatform.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsplatform_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssettings.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_linguist.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_location.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_mqtt.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_mqtt_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_network.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_networkauth.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_nfc.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opcua.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opcua_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_png_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobuf.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobuf_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtcoretypes.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtguitypes.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufwellknowntypes.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcompiler.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlintegration.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmeta.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlnetwork.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3d.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3deffects.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticles.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysics.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickeffects_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimeline.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickvectorimage.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_repparser.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxmlqml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensorsquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_serialbus.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_shadertools.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_shadertools_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_spatialaudio.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachine.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachine_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachineqml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_tools_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_vncserver.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_vncserver_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_vncserverquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannelquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webview.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webviewquick.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_webviewquick_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_assimp.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_darwinmediaplugin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_ffmpegmediaplugin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_open62541_backend.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_openglrenderer.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qcertonlybackend.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qgif.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_quick3dprofiler.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qscnetworkreachability.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qscxmlecmascriptdatamodel.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsecuretransportbackend.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_mock.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechdarwin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtposition_nmea.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qttinycanbus.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_quicklintplugin.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_rhirenderer.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/modules/qt_plugin_scene2d.pri:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qt_functions.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qt_config.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-xcode/qmake.conf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/exclusive_builds.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/sdk.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/sdk.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/toolchain.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/toolchain.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/default_pre.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/default_pre.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/default_pre.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/resolve_config.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/resolve_config.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/default_post.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/default_post.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/default_post.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/objective_c.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qml_debug.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/mac.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/warn_on.prf:
../../iosInfo.plist:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/permissions.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qt.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/resources_functions.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/resources.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/moc.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/unix/opengl.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/unix/thread.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/qmake_use.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/file_copies.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/rez.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/mac/asset_catalogs.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/testcase_targets.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/uikit/testcase_targets.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/exceptions.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/yacc.prf:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/features/lex.prf:
../../homework-qmake.pro:
/Users/stephenzeng/Qt/6.8.0/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard:
../../icons.qrc:
qmake_resources.qrc:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/permissions/libqdarwinbluetoothpermission.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/platforms/libqios.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/iconengines/libqsvgicon.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqgif.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqicns.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqico.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqjpeg.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqmacheif.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqmacjp2.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqsvg.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqtga.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqtiff.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqwbmp.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/imageformats/libqwebp.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_debugger.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_inspector.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_local.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_messages.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_native.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_preview.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_profiler.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_quick3dprofiler.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_server.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/qmltooling/libqmldbg_tcp.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/networkinformation/libqscnetworkreachability.prl:
/Users/stephenzeng/Qt/6.8.0/ios/plugins/tls/libqsecuretransportbackend.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/libqtquick2plugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQml/libqmlplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQml/Models/libmodelsplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQml/WorkerScript/libworkerscriptplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Dialogs/libqtquickdialogsplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Dialogs/quickimpl/libqtquickdialogs2quickimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Templates/libqtquicktemplates2plugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/libqtquickcontrols2plugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/impl/libqtquickcontrols2implplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Material/impl/libqtquickcontrols2materialstyleimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Imagine/impl/libqtquickcontrols2imaginestyleimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Fusion/impl/libqtquickcontrols2fusionstyleimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/FluentWinUI3/libqtquickcontrols2fluentwinui3styleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/iOS/libqtquickcontrols2iosstyleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Basic/libqtquickcontrols2basicstyleplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Universal/impl/libqtquickcontrols2universalstyleimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Window/libquickwindowplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/FluentWinUI3/impl/libqtquickcontrols2fluentwinui3styleimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Effects/libeffectsplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Shapes/libqmlshapesplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/iOS/impl/libqtquickcontrols2iosstyleimplplugin.prl:
/Users/stephenzeng/Qt/6.8.0/ios/qml/QtQuick/Controls/Basic/impl/libqtquickcontrols2basicstyleimplplugin.prl:
qmake: FORCE
	@$(QMAKE) -o homework-qmake.xcodeproj/project.pbxproj ../../homework-qmake.pro -spec macx-xcode -qtconf /Users/stephenzeng/Qt/6.8.0/ios/bin/target_qt.conf CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after

qmake_all: FORCE

